# Generated by Django 5.2.17 on 2026-09-23 14:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0007_booking_is_walk_in_alter_booking_customer_and_more'),
        ('menu', '0002_seed_menu_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Đang phục vụ'), ('AWAITING_PAYMENT', 'Chờ thanh toán'), ('VOID', 'Đã hủy')], default='OPEN', max_length=20, verbose_name='Trạng thái')),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Mở lúc')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='bookings.booking', verbose_name='Lượt khách')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'đơn hàng',
                'verbose_name_plural': 'đơn hàng',
                'ordering': ('-created_at', '-pk'),
                'permissions': [('manage_order', 'Mở đơn và gọi món'), ('work_kitchen', 'Xử lý món tại Bếp'), ('cancel_prepared_item', 'Hủy món đã bắt đầu làm')],
            },
        ),
        migrations.CreateModel(
            name='OrderActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Thao tác')),
                ('description', models.TextField(verbose_name='Nội dung')),
                ('actor_snapshot', models.CharField(max_length=150, verbose_name='Người thực hiện')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_logs', to='orders.order')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'nhật ký đơn hàng',
                'verbose_name_plural': 'nhật ký đơn hàng',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_code', models.CharField(max_length=20)),
                ('dish_name', models.CharField(max_length=150)),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=9, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Số lượng')),
                ('note', models.TextField(blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Ghi chú cho Bếp')),
                ('status', models.CharField(choices=[('DRAFT', 'Chưa gửi Bếp'), ('SENT', 'Đã gửi Bếp'), ('COOKING', 'Đang làm'), ('READY', 'Đã xong'), ('SERVED', 'Đã phục vụ'), ('CANCELLED', 'Đã hủy')], default='DRAFT', max_length=10, verbose_name='Trạng thái')),
                ('cancellation_reason', models.CharField(blank=True, max_length=500, verbose_name='Lý do hủy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menu.dish', verbose_name='Món')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'món trong đơn',
                'verbose_name_plural': 'món trong đơn',
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'AWAITING_PAYMENT', 'VOID'])), name='order_valid_status'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['status', 'sent_at'], name='order_kitchen_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 100)), name='order_item_quantity_range'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 1), ('unit_price__lte', 999999999)), name='order_item_price_range'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'SENT', 'COOKING', 'READY', 'SERVED', 'CANCELLED'])), name='order_item_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELLED'), _negated=True), models.Q(('cancellation_reason__regex', '\\S'), ('cancelled_at__isnull', False)), _connector='OR'), name='order_item_cancel_reason'),
        ),
    ]
