# Generated by Django 5.2.17 on 2026-09-25 08:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_seed_order_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_code', models.CharField(max_length=20, unique=True, verbose_name='Mã hóa đơn')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999)], verbose_name='Tổng tiền')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999)], verbose_name='Đã thu')),
                ('status', models.CharField(choices=[('PENDING', 'Chưa thu tiền'), ('PAID', 'Đã thanh toán'), ('VOID', 'Hủy hóa đơn')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('payment_method', models.CharField(blank=True, default='CASH', max_length=20, verbose_name='Phương thức thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian chốt')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'hóa đơn',
                'verbose_name_plural': 'hóa đơn',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999999)], verbose_name='Số tiền')),
                ('method', models.CharField(choices=[('CASH', 'Tiền mặt'), ('CARD', 'Thẻ'), ('TRANSFER', 'Chuyển khoản'), ('OTHER', 'Khác')], default='CASH', max_length=20, verbose_name='Phương thức')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Ghi chú / mã giao dịch')),
                ('actor_snapshot', models.CharField(blank=True, max_length=150, verbose_name='Người thực hiện')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian thanh toán')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.invoice')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'phiếu thu',
                'verbose_name_plural': 'phiếu thu',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
