# Generated by Django 5.2.17 on 2026-10-01 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_image_dish_thumbnail'),
        ('orders', '0014_order_split_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='seat_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Số ghế/vị trí của khách trong bàn; bỏ trống nếu là món dùng chung.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Vị trí khách'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('seat_number__isnull', True), models.Q(('seat_number__gte', 1), ('seat_number__lte', 100)), _connector='OR'), name='order_item_seat_range'),
        ),
    ]
