# Generated by Django 5.2.17 on 2026-10-01 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_image_dish_thumbnail'),
        ('orders', '0015_orderitem_seat_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='inventory_deducted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Đã trừ kho lúc'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='inventory_returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Đã hoàn kho lúc'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tổng giá vốn'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost_snapshot',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá vốn một món'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost_snapshot__gte', 0)), name='order_item_unit_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='order_item_total_cost_nonnegative'),
        ),
    ]
