# Generated by Django 5.2.17 on 2026-10-02 08:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_seed_default_membership_tiers'),
        ('menu', '0003_dish_image_dish_thumbnail'),
        ('orders', '0016_orderitem_inventory_deducted_at_and_more'),
        ('seating', '0004_diningtableqrtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QROrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING_CONFIRMATION', 'Chờ nhân viên xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('REJECTED', 'Đã từ chối'), ('CANCELLED', 'Đã hủy')], db_index=True, default='WAITING_CONFIRMATION', max_length=24)),
                ('note', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=500)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_qr_order_requests', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_order_requests', to='customers.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qr_order_requests', to='orders.order')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_qr_order_requests', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qr_order_requests', to='seating.diningtable')),
            ],
            options={
                'verbose_name': 'yêu cầu gọi món QR',
                'verbose_name_plural': 'yêu cầu gọi món QR',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='QROrderRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('note', models.TextField(blank=True, max_length=500)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=0, max_digits=9, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qr_order_request_items', to='menu.dish')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.qrorderrequest')),
            ],
            options={
                'verbose_name': 'món trong yêu cầu QR',
                'verbose_name_plural': 'món trong yêu cầu QR',
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='qrorderrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('WAITING_CONFIRMATION', 'CONFIRMED', 'REJECTED', 'CANCELLED'))), name='qr_request_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='qrorderrequestitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 100)), name='qr_request_item_quantity_range'),
        ),
        migrations.AddConstraint(
            model_name='qrorderrequestitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_snapshot__gte', 1)), name='qr_request_item_price_positive'),
        ),
    ]
