# Generated by Django 5.2.17 on 2026-10-02 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_qrorderrequest_qrorderrequestitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrorderrequestitem',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_request_item', to='orders.orderitem'),
        ),
    ]
