# Generated by Django 5.2.17 on 2026-10-08

import apps.orders.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_qrorderrequestitem_order_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCheckInRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guest_count", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ("status", models.CharField(choices=[("WAITING_CONFIRMATION", "Chờ nhân viên nhận bàn"), ("CONFIRMED", "Đã nhận bàn"), ("REJECTED", "Đã từ chối"), ("EXPIRED", "Đã hết hạn")], db_index=True, default="WAITING_CONFIRMATION", max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True, default=apps.orders.models.default_qr_check_in_expiry)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("reject_reason", models.CharField(blank=True, max_length=500)),
                ("confirmed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="confirmed_qr_check_in_requests", to=settings.AUTH_USER_MODEL)),
                ("order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="qr_check_in_requests", to="orders.order")),
                ("rejected_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="rejected_qr_check_in_requests", to=settings.AUTH_USER_MODEL)),
                ("table", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="qr_check_in_requests", to="seating.diningtable")),
            ],
            options={
                "verbose_name": "yêu cầu nhận bàn QR",
                "verbose_name_plural": "yêu cầu nhận bàn QR",
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.AddConstraint(
            model_name="qrcheckinrequest",
            constraint=models.CheckConstraint(condition=models.Q(("guest_count__gte", 1), ("guest_count__lte", 100)), name="qr_check_in_guest_count_range"),
        ),
        migrations.AddConstraint(
            model_name="qrcheckinrequest",
            constraint=models.CheckConstraint(condition=models.Q(("status__in", ("WAITING_CONFIRMATION", "CONFIRMED", "REJECTED", "EXPIRED"))), name="qr_check_in_valid_status"),
        ),
        migrations.AddConstraint(
            model_name="qrcheckinrequest",
            constraint=models.UniqueConstraint(condition=models.Q(("status", "WAITING_CONFIRMATION")), fields=("table",), name="one_waiting_qr_check_in_per_table"),
        ),
    ]
