# Generated by Django 5.2.17 on 2026-09-21 11:54

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'nhóm món',
                'verbose_name_plural': 'nhóm món',
                'ordering': ('name', 'pk'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='menu_category_name_unique', violation_error_message='Tên đã tồn tại.'), models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='menu_category_name_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='MenuActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('CATEGORY', 'Nhóm món'), ('UNIT', 'Đơn vị tính'), ('DISH', 'Món')], max_length=10, verbose_name='Loại')),
                ('object_id', models.PositiveBigIntegerField()),
                ('label_snapshot', models.CharField(max_length=180, verbose_name='Tên tại thời điểm thao tác')),
                ('action', models.CharField(max_length=40, verbose_name='Hành động')),
                ('description', models.TextField(verbose_name='Nội dung')),
                ('actor_snapshot', models.CharField(max_length=150, verbose_name='Người thực hiện')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'nhật ký thực đơn',
                'verbose_name_plural': 'nhật ký thực đơn',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'đơn vị tính',
                'verbose_name_plural': 'đơn vị tính',
                'ordering': ('name', 'pk'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='menu_unit_name_unique', violation_error_message='Tên đã tồn tại.'), models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='menu_unit_name_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(error_messages={'unique': 'Mã món đã tồn tại.'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('\\A[A-Z0-9][A-Z0-9_-]{0,19}\\Z', 'Mã món chỉ gồm chữ A–Z, số, gạch ngang hoặc gạch dưới; bắt đầu bằng chữ hoặc số.')], verbose_name='Mã món')),
                ('name', models.CharField(max_length=150, verbose_name='Tên món')),
                ('price', models.DecimalField(decimal_places=0, max_digits=9, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)], verbose_name='Giá bán (đồng)')),
                ('description', models.TextField(blank=True, max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Mô tả')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Còn món'), ('SOLD_OUT', 'Hết món'), ('INACTIVE', 'Ngừng bán')], default='AVAILABLE', max_length=10, verbose_name='Trạng thái')),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='menu.category', verbose_name='Nhóm món')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='menu.unit', verbose_name='Đơn vị tính')),
            ],
            options={
                'verbose_name': 'món',
                'verbose_name_plural': 'món',
                'ordering': ('category__name', 'name', 'pk'),
                'permissions': [('manage_menu', 'Quản lý thực đơn và giá bán'), ('change_availability', 'Cập nhật còn món / hết món')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 1), ('price__lte', 999999999)), name='menu_dish_price_range'), models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z0-9][A-Z0-9_-]{0,19}$')), name='menu_dish_code_canonical'), models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='menu_dish_name_not_blank'), models.CheckConstraint(condition=models.Q(('status__in', ['AVAILABLE', 'SOLD_OUT', 'INACTIVE'])), name='menu_dish_valid_status')],
            },
        ),
    ]
