# Generated by Django 5.2.17 on 2026-09-25 08:13

import apps.menu.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_seed_menu_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, upload_to='dishes/', validators=[apps.menu.images.validate_upload_size], verbose_name='Ảnh món'),
        ),
        migrations.AddField(
            model_name='dish',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='dishes/'),
        ),
    ]
