# Generated by Django 5.2.17 on 2026-09-20 14:23

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khu vực')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'khu vực',
                'verbose_name_plural': 'khu vực',
                'ordering': ('name', 'pk'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='seating_area_name_unique', violation_error_message='Tên khu vực đã tồn tại.'), models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='seating_area_name_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='SeatingActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('AREA', 'Khu vực'), ('TABLE', 'Bàn')], max_length=10, verbose_name='Loại')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='ID đối tượng')),
                ('label_snapshot', models.CharField(max_length=100, verbose_name='Tên / mã tại thời điểm thao tác')),
                ('action', models.CharField(choices=[('CREATE', 'Thêm mới'), ('UPDATE', 'Cập nhật')], max_length=10, verbose_name='Hành động')),
                ('description', models.TextField(verbose_name='Nội dung')),
                ('actor_snapshot', models.CharField(max_length=150, verbose_name='Người thực hiện')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'nhật ký khu vực và bàn',
                'verbose_name_plural': 'nhật ký khu vực và bàn',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(error_messages={'unique': 'Mã bàn đã tồn tại.'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('\\A[A-Z0-9][A-Z0-9_-]{0,19}\\Z', 'Mã bàn chỉ gồm chữ A–Z, số, dấu gạch ngang hoặc gạch dưới; bắt đầu bằng chữ hoặc số.')], verbose_name='Mã bàn')),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Số chỗ ngồi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='seating.area', verbose_name='Khu vực')),
            ],
            options={
                'verbose_name': 'bàn',
                'verbose_name_plural': 'bàn',
                'ordering': ('area__name', 'code', 'pk'),
                'permissions': [('manage_seating', 'Quản lý khu vực và bàn')],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gte', 1), ('capacity__lte', 100)), name='seating_capacity_range'), models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z0-9][A-Z0-9_-]{0,19}$')), name='seating_code_canonical')],
            },
        ),
    ]
