# Generated by Django 5.2.17 on 2026-10-02 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_table_tokens(apps, schema_editor):
    DiningTable = apps.get_model("seating", "DiningTable")
    DiningTableQRToken = apps.get_model("seating", "DiningTableQRToken")
    DiningTableQRToken.objects.bulk_create(
        [DiningTableQRToken(table_id=table_id) for table_id in DiningTable.objects.values_list("pk", flat=True)]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0003_table_operational_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningTableQRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_token', to='seating.diningtable')),
            ],
            options={
                'verbose_name': 'mã QR bàn',
                'verbose_name_plural': 'mã QR bàn',
                'ordering': ('table__code', 'pk'),
            },
        ),
        migrations.RunPython(create_table_tokens, migrations.RunPython.noop),
    ]
