# Generated by Django 5.2.17 on 2026-09-20 14:02

import apps.customers.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='họ tên')),
                ('phone', models.CharField(error_messages={'unique': 'Số điện thoại đã có hồ sơ khách hàng. Hãy tìm khách theo số điện thoại.'}, max_length=20, unique=True, validators=[apps.customers.validators.validate_phone], verbose_name='số điện thoại')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'khách hàng',
                'verbose_name_plural': 'khách hàng',
                'ordering': ('-created_at', '-pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('phone__regex', '^0[0-9]{9,10}$')), name='customers_phone_canonical'), models.CheckConstraint(condition=models.Q(('full_name__regex', '\\S')), name='customers_name_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='CustomerActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code_snapshot', models.CharField(max_length=30, verbose_name='mã khách hàng')),
                ('customer_name_snapshot', models.CharField(max_length=150, verbose_name='tên khách hàng')),
                ('performed_by_name_snapshot', models.CharField(max_length=301, verbose_name='người thực hiện')),
                ('action', models.CharField(choices=[('CREATE', 'Thêm khách hàng'), ('UPDATE', 'Sửa khách hàng'), ('DELETE', 'Xóa khách hàng')], max_length=10, verbose_name='hành động')),
                ('description', models.TextField(verbose_name='mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='thời gian')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='customers.customer')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'nhật ký khách hàng',
                'verbose_name_plural': 'nhật ký khách hàng',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
