# Generated by Django 5.2.17 on 2026-09-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('employees', '0003_jobposition_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='accounts_user_role_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='accounts_superuser_manager_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
