# Generated by Django 5.2.17 on 2026-10-01 06:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_correct_permissions'),
        ('menu', '0003_dish_image_dish_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Định lượng cho một món')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'định lượng món',
                'verbose_name_plural': 'định lượng món',
                'ordering': ('ingredient__name', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='average_unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá vốn bình quân'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='order_item_reference',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='Mã dòng món liên quan'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IMPORT', 'Nhập kho'), ('EXPORT', 'Xuất kho'), ('ADJUSTMENT', 'Điều chỉnh'), ('SALE_USAGE', 'Xuất theo món bán'), ('SALE_RETURN', 'Hoàn do hủy món')], max_length=16, verbose_name='Loại giao dịch'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(condition=models.Q(('average_unit_cost__gte', 0)), name='inventory_average_cost_nonnegative'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='menu.dish', verbose_name='Món'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_lines', to='inventory.ingredient', verbose_name='Nguyên liệu'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('dish', 'ingredient'), name='inventory_recipe_dish_ingredient_unique'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_recipe_quantity_positive'),
        ),
    ]
