# Generated by Django 5.2.17 on 2026-10-01 06:56

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_recipeingredient_ingredient_average_unit_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='code',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('\\A[A-Z0-9][A-Z0-9_-]{0,19}\\Z', 'Mã chỉ gồm chữ A–Z, số, gạch ngang hoặc gạch dưới.')], verbose_name='Mã nguyên liệu'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z0-9][A-Z0-9_-]{0,19}$')), name='inventory_ingredient_code_canonical'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='inventory_ingredient_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(condition=models.Q(('unit__regex', '\\S')), name='inventory_ingredient_unit_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='inventory_supplier_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='inventory_supplier_name_not_blank'),
        ),
    ]
