# Generated by Django 5.2.17 on 2026-10-01 07:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_ingredient_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='source_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='Mã chứng từ'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='source_type',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Loại chứng từ'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IMPORT', 'Nhập kho'), ('EXPORT', 'Xuất kho'), ('ADJUSTMENT', 'Điều chỉnh'), ('SALE_USAGE', 'Xuất theo món bán'), ('SALE_RETURN', 'Hoàn do hủy món'), ('PURCHASE', 'Nhận hàng'), ('STOCKTAKE', 'Chênh lệch kiểm kê'), ('WASTE', 'Hao hụt / hư hỏng')], max_length=16, verbose_name='Loại giao dịch'),
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã phiếu nhập')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Số hóa đơn nhà cung cấp')),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('RECEIVED', 'Đã nhận hàng'), ('CANCELLED', 'Đã hủy')], db_index=True, default='DRAFT', max_length=12, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, max_length=500, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_purchase_receipts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_receipts', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to='inventory.supplier', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'phiếu nhập hàng',
                'verbose_name_plural': 'phiếu nhập hàng',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocktake_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã kiểm kê')),
                ('status', models.CharField(choices=[('DRAFT', 'Đang kiểm'), ('POSTED', 'Đã chốt'), ('CANCELLED', 'Đã hủy')], db_index=True, default='DRAFT', max_length=12, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, max_length=500, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stocktakes', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_stocktakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã hao hụt')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Số lượng')),
                ('reason', models.CharField(choices=[('SPOILED', 'Hư hỏng'), ('EXPIRED', 'Hết hạn'), ('PREPARATION', 'Hao hụt sơ chế'), ('BREAKAGE', 'Đổ vỡ'), ('STAFF', 'Nhân viên sử dụng'), ('OTHER', 'Khác')], max_length=20, verbose_name='Nguyên nhân')),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá vốn')),
                ('total_cost', models.DecimalField(decimal_places=0, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá trị hao hụt')),
                ('note', models.TextField(blank=True, max_length=500, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_records', to='inventory.ingredient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Số lượng')),
                ('unit_cost', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Đơn giá')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='inventory.ingredient')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchasereceipt')),
            ],
            options={
                'ordering': ('pk',),
                'constraints': [models.UniqueConstraint(fields=('receipt', 'ingredient'), name='inventory_purchase_line_unique'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_purchase_quantity_positive'), models.CheckConstraint(condition=models.Q(('unit_cost__gt', 0)), name='inventory_purchase_cost_positive')],
            },
        ),
        migrations.CreateModel(
            name='StocktakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Tồn hệ thống khi chốt')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tồn thực tế')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_lines', to='inventory.ingredient')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktake')),
            ],
            options={
                'ordering': ('ingredient__name', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('stocktake', 'ingredient'), name='inventory_stocktake_line_unique')],
            },
        ),
    ]
