# Generated by Django 5.2.17 on 2026-09-20 14:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_seed_customer_permissions'),
        ('seating', '0002_seed_seating_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Tên khách khi đặt')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Điện thoại khi đặt')),
                ('party_size', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Số khách')),
                ('starts_at', models.DateTimeField(verbose_name='Giờ đến')),
                ('ends_at', models.DateTimeField(verbose_name='Giờ kết thúc dự kiến')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('SEATED', 'Đã nhận khách'), ('COMPLETED', 'Hoàn tất'), ('CANCELLED', 'Đã hủy'), ('NO_SHOW', 'Không đến')], default='PENDING', max_length=12, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customers.customer', verbose_name='Khách hàng')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='seating.diningtable', verbose_name='Bàn')),
            ],
            options={
                'verbose_name': 'đặt bàn',
                'verbose_name_plural': 'đặt bàn',
                'ordering': ('-starts_at', '-pk'),
                'permissions': [('manage_booking', 'Tạo và cập nhật đặt bàn')],
            },
        ),
        migrations.CreateModel(
            name='BookingActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Thao tác')),
                ('description', models.TextField(verbose_name='Nội dung')),
                ('actor_snapshot', models.CharField(max_length=150, verbose_name='Người thực hiện')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_logs', to='bookings.booking')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'nhật ký đặt bàn',
                'verbose_name_plural': 'nhật ký đặt bàn',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['table', 'status', 'starts_at', 'ends_at'], name='booking_slot_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='booking_time_order'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('party_size__gte', 1), ('party_size__lte', 100)), name='booking_party_range'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED', 'SEATED', 'COMPLETED', 'CANCELLED', 'NO_SHOW'])), name='booking_valid_status'),
        ),
    ]
