# Generated by Django 5.2.17 on 2026-09-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_seed_booking_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='revision',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
