# Generated by Django 5.2.17 on 2026-09-20 14:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('SEATED', 'Đang phục vụ'), ('COMPLETED', 'Hoàn tất'), ('CANCELLED', 'Đã hủy'), ('NO_SHOW', 'Không đến')], default='PENDING', max_length=12, verbose_name='Trạng thái'),
        ),
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_duration_minutes', models.PositiveSmallIntegerField(default=120, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Thời lượng mặc định (phút)')),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cấu hình đặt bàn',
                'verbose_name_plural': 'cấu hình đặt bàn',
                'permissions': [('configure_bookings', 'Cấu hình thời lượng đặt bàn')],
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='booking_settings_singleton'), models.CheckConstraint(condition=models.Q(('default_duration_minutes__gte', 1), ('default_duration_minutes__lte', 1440)), name='booking_default_duration_range')],
            },
        ),
        migrations.CreateModel(
            name='BookingSettingsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_minutes', models.PositiveSmallIntegerField()),
                ('new_minutes', models.PositiveSmallIntegerField()),
                ('actor_snapshot', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
