# Generated by Django 5.2.17 on 2026-09-21 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_seed_booking_settings'),
        ('customers', '0002_seed_customer_permissions'),
        ('seating', '0002_seed_seating_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Giờ khách rời bàn'),
        ),
        migrations.AddField(
            model_name='booking',
            name='seated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Giờ nhận khách thực tế'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('seated_at__isnull', True), ('completed_at__gte', models.F('seated_at')), _connector='OR'), name='booking_actual_time_order'),
        ),
    ]
