# Generated by Django 5.2.17 on 2026-09-23 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_completed_at_booking_seated_at_and_more'),
        ('customers', '0002_seed_customer_permissions'),
        ('seating', '0002_seed_seating_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_walk_in',
            field=models.BooleanField(default=False, editable=False, verbose_name='Khách không đặt trước'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customers.customer', verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Điện thoại khi đặt'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('is_walk_in', True), ('customer__isnull', False), _connector='OR'), name='booking_reserved_customer_required'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('is_walk_in', False), ('status__in', ['SEATED', 'COMPLETED']), _connector='OR'), name='booking_walk_in_status'),
        ),
    ]
