# Generated by Django 5.2.17 on 2026-09-17 02:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='mã nhân viên')),
                ('full_name', models.CharField(max_length=150, verbose_name='họ và tên')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^0[0-9]{9,10}$', 'Số điện thoại không hợp lệ.')], verbose_name='số điện thoại')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='địa chỉ')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='ngày sinh')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('OTHER', 'Khác')], max_length=10, verbose_name='giới tính')),
                ('job_position', models.CharField(choices=[('MANAGER', 'Quản lý'), ('WAITER', 'Phục vụ'), ('CASHIER', 'Thu ngân'), ('KITCHEN', 'Bếp'), ('INVENTORY', 'Kho')], max_length=20, verbose_name='vị trí')),
                ('join_date', models.DateField(verbose_name='ngày vào làm')),
                ('employment_status', models.CharField(choices=[('WORKING', 'Đang làm việc'), ('ON_LEAVE', 'Tạm nghỉ'), ('RESIGNED', 'Đã nghỉ việc')], default='WORKING', max_length=20, verbose_name='trạng thái')),
                ('avatar', models.ImageField(blank=True, upload_to='employees/', verbose_name='ảnh đại diện')),
                ('note', models.TextField(blank=True, verbose_name='ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='cập nhật lần cuối')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('employee_code', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='EmployeeActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Tạo mới'), ('UPDATE', 'Cập nhật'), ('RESIGN', 'Nghỉ việc'), ('STATUS', 'Đổi trạng thái')], max_length=20, verbose_name='hành động')),
                ('description', models.TextField(verbose_name='mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='thời gian')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_logs', to='employees.employeeprofile')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['full_name'], name='employees_e_full_na_f081ac_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['phone'], name='employees_e_phone_d3f186_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['employment_status'], name='employees_e_employm_729ebb_idx'),
        ),
    ]
