# Generated by Django 5.2.17 on 2026-09-17 02:44

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='resignation_date',
            field=models.DateField(blank=True, null=True, verbose_name='ngày nghỉ việc'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^0[0-9]{9,10}$', 'Số điện thoại không hợp lệ.')], verbose_name='số điện thoại'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['job_position'], name='employees_e_job_pos_c9abf4_idx'),
        ),
    ]
