# Generated by Django 5.2.17 on 2026-09-17 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


POSITION_NAMES = {
    "MANAGER": "Quản trị viên / Quản lý",
    "WAITER": "Phục vụ",
    "CASHIER": "Thu ngân",
    "KITCHEN": "Bếp",
    "INVENTORY": "Kho",
}


def create_positions_and_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    JobPosition = apps.get_model("employees", "JobPosition")
    for code, name in POSITION_NAMES.items():
        group, _ = Group.objects.get_or_create(name=code)
        JobPosition.objects.get_or_create(code=code, defaults={"name": name, "group_id": group.pk})


def copy_position_codes(apps, schema_editor):
    EmployeeProfile = apps.get_model("employees", "EmployeeProfile")
    JobPosition = apps.get_model("employees", "JobPosition")
    User = apps.get_model("accounts", "User")
    for employee in EmployeeProfile.objects.select_related("user"):
        code = employee.job_position
        if code not in POSITION_NAMES:
            code = "MANAGER" if getattr(employee.user, "role", "EMPLOYEE") == "MANAGER" else "WAITER"
        position = JobPosition.objects.get(code=code)
        EmployeeProfile.objects.filter(pk=employee.pk).update(job_position_new_id=position.pk)


def copy_log_snapshots(apps, schema_editor):
    Log = apps.get_model("employees", "EmployeeActivityLog")
    for log in Log.objects.select_related("employee", "performed_by"):
        employee = log.employee
        log.employee_code_snapshot = employee.employee_code if employee else ""
        log.employee_name_snapshot = employee.full_name if employee else ""
        if log.performed_by:
            name = f"{log.performed_by.first_name} {log.performed_by.last_name}".strip()
            log.performed_by_name_snapshot = name or log.performed_by.username
        else:
            log.performed_by_name_snapshot = ""
        log.save(update_fields=("employee_code_snapshot", "employee_name_snapshot", "performed_by_name_snapshot"))


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employees', '0002_employeeprofile_resignation_date_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='mã vị trí')),
                ('name', models.CharField(max_length=100, verbose_name='tên vị trí')),
                ('description', models.TextField(blank=True, verbose_name='mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='cập nhật lần cuối')),
            ],
            options={
                'ordering': ('code', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='employeeactivitylog',
            name='employee_code_snapshot',
            field=models.CharField(default='', max_length=20, verbose_name='mã nhân viên'),
        ),
        migrations.AddField(
            model_name='employeeactivitylog',
            name='employee_name_snapshot',
            field=models.CharField(default='', max_length=150, verbose_name='tên nhân viên'),
        ),
        migrations.AddField(
            model_name='employeeactivitylog',
            name='performed_by_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='người thực hiện'),
        ),
        migrations.AlterField(
            model_name='employeeactivitylog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Tạo mới'), ('UPDATE', 'Cập nhật'), ('CHANGE_POSITION', 'Đổi vị trí'), ('RESET_PASSWORD', 'Đặt lại mật khẩu'), ('LOCK_ACCOUNT', 'Khóa tài khoản'), ('UNLOCK_ACCOUNT', 'Mở khóa tài khoản'), ('RESIGN', 'Nghỉ việc'), ('STATUS', 'Đổi trạng thái'), ('DELETE', 'Xóa nhân viên')], max_length=20, verbose_name='hành động'),
        ),
        migrations.AlterField(
            model_name='employeeactivitylog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='employees.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='employeeactivitylog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobposition', name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_position', to='auth.group'),
        ),
        migrations.AddField(
            model_name='employeeprofile', name='job_position_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.jobposition'),
        ),
        migrations.RunPython(create_positions_and_groups, migrations.RunPython.noop),
        migrations.RunPython(copy_position_codes, migrations.RunPython.noop),
        migrations.RunPython(copy_log_snapshots, migrations.RunPython.noop),
        migrations.RemoveField(model_name='employeeprofile', name='job_position'),
        migrations.RenameField(model_name='employeeprofile', old_name='job_position_new', new_name='job_position'),
        migrations.AlterField(
            model_name='employeeprofile', name='job_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.jobposition', verbose_name='vị trí'),
        ),
        migrations.AlterField(
            model_name='jobposition', name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='job_position', to='auth.group'),
        ),
        migrations.AddIndex(model_name='employeeprofile', index=models.Index(fields=['job_position'], name='employees_e_job_pos_437c9f_idx')),
    ]
