# Generated by Django 5.2.17 on 2026-09-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_seed_job_position_permissions'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employeeprofile',
            name='employees_e_job_pos_c9abf4_idx',
        ),
    ]
